from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import BookList, BookViewSet

router = DefaultRouter()
router.register(r'books_all', BookViewSet, basename='book_all')

urlpatterns = [
    # Route for the ListAPIView (previous step)
    path('books/', BookList.as_view(), name='book-list'),

    # Routes generated by the router
    path('', include(router.urls)),
]
