from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import BookList, BookViewSet
from rest_framework.authtoken.views import obtain_auth_token   # ✅ new import

router = DefaultRouter()
router.register(r'books_all', BookViewSet, basename='book_all')

urlpatterns = [
    # Route for the ListAPIView (previous step)
    path('books/', BookList.as_view(), name='book-list'),

    # Routes generated by the router
    path('', include(router.urls)),

    # ✅ Token authentication endpoint
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
]
